name: plate_planner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_verification_code: ^1.1.6
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  swipeable_card_stack: ^0.0.5
  flutter_swipable: ^1.2.1
  swipable_stack: ^2.0.0
  firebase_messaging: ^14.7.2
  firebase_analytics: ^10.6.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

