// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjV1IBnf-sxdm8NbH_jQt0C9kF1cu3I10',
    appId: '1:963216143898:web:598892b235918464bd43a3',
    messagingSenderId: '963216143898',
    projectId: 'plateplanner-b9685',
    authDomain: 'plateplanner-b9685.firebaseapp.com',
    storageBucket: 'plateplanner-b9685.appspot.com',
    measurementId: 'G-0RG6836RG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwZ59sgti-H7YNB62ailTfryRJjeKodA',
    appId: '1:963216143898:android:771f34ff2e342ec1bd43a3',
    messagingSenderId: '963216143898',
    projectId: 'plateplanner-b9685',
    storageBucket: 'plateplanner-b9685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlXO9uLy99oa6qSjN7MspbcOOqK1y7woE',
    appId: '1:963216143898:ios:6894a8f03c1e0b2ebd43a3',
    messagingSenderId: '963216143898',
    projectId: 'plateplanner-b9685',
    storageBucket: 'plateplanner-b9685.appspot.com',
    iosBundleId: 'com.plates.platePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlXO9uLy99oa6qSjN7MspbcOOqK1y7woE',
    appId: '1:963216143898:ios:d694319b0979dfe1bd43a3',
    messagingSenderId: '963216143898',
    projectId: 'plateplanner-b9685',
    storageBucket: 'plateplanner-b9685.appspot.com',
    iosBundleId: 'com.plates.platePlanner.RunnerTests',
  );
}
